set_property -dict {PACKAGE_PIN AB16 IOSTANDARD LVCMOS18} [get_ports clk]
set_property -dict {PACKAGE_PIN AF13 IOSTANDARD LVCMOS15} [get_ports rstn]

set_property -dict {PACKAGE_PIN AD23 IOSTANDARD LVCMOS33} [get_ports {seg_sout[2]}]
set_property -dict {PACKAGE_PIN AD21 IOSTANDARD LVCMOS33} [get_ports {seg_sout[1]}]
set_property -dict {PACKAGE_PIN AD5 IOSTANDARD LVCMOS15} [get_ports {seg_sout[0]}]

set_property -dict {PACKAGE_PIN AB21 IOSTANDARD LVCMOS33} [get_ports {led_sout[2]}]
set_property -dict {PACKAGE_PIN AA23 IOSTANDARD LVCMOS33} [get_ports {led_sout[1]}]
set_property -dict {PACKAGE_PIN W13 IOSTANDARD LVCMOS18} [get_ports {led_sout[0]}]

set_property -dict {PACKAGE_PIN J10 IOSTANDARD LVCMOS33} [get_ports {segment[7]}]
set_property -dict {PACKAGE_PIN J11 IOSTANDARD LVCMOS33} [get_ports {segment[6]}]
set_property -dict {PACKAGE_PIN J8 IOSTANDARD LVCMOS33} [get_ports {segment[5]}]
set_property -dict {PACKAGE_PIN H8 IOSTANDARD LVCMOS33} [get_ports {segment[4]}]
set_property -dict {PACKAGE_PIN H9 IOSTANDARD LVCMOS33} [get_ports {segment[3]}]
set_property -dict {PACKAGE_PIN G9 IOSTANDARD LVCMOS33} [get_ports {segment[2]}]
set_property -dict {PACKAGE_PIN G10 IOSTANDARD LVCMOS33} [get_ports {segment[1]}]
set_property -dict {PACKAGE_PIN H11 IOSTANDARD LVCMOS33} [get_ports {segment[0]}]

#set_property -dict {PACKAGE_PIN F10 IOSTANDARD LVCMOS33} [get_ports {anode[3]}]
#set_property -dict {PACKAGE_PIN G11 IOSTANDARD LVCMOS33} [get_ports {anode[2]}]
set_property -dict {PACKAGE_PIN G11 IOSTANDARD LVCMOS33} [get_ports {anode[1]}]
set_property -dict {PACKAGE_PIN F10 IOSTANDARD LVCMOS33} [get_ports {anode[0]}]

set_property -dict {PACKAGE_PIN D9 IOSTANDARD LVCMOS33} [get_ports {LED[7]}]
set_property -dict {PACKAGE_PIN D8 IOSTANDARD LVCMOS33} [get_ports {LED[6]}]
set_property -dict {PACKAGE_PIN F9 IOSTANDARD LVCMOS33} [get_ports {LED[5]}]
set_property -dict {PACKAGE_PIN F8 IOSTANDARD LVCMOS33} [get_ports {LED[4]}]
set_property -dict {PACKAGE_PIN C12 IOSTANDARD LVCMOS33} [get_ports {LED[3]}]
set_property -dict {PACKAGE_PIN E13 IOSTANDARD LVCMOS33} [get_ports {LED[2]}]
set_property -dict {PACKAGE_PIN H13 IOSTANDARD LVCMOS33} [get_ports {LED[1]}]
set_property -dict {PACKAGE_PIN J13 IOSTANDARD LVCMOS33} [get_ports {LED[0]}]

#set_property -dict {PACKAGE_PIN AF24 IOSTANDARD LVCMOS33} [get_ports buzzer]

set_property -dict {PACKAGE_PIN AF20 IOSTANDARD LVCMOS18} [get_ports {btnY[4]}]
set_property -dict {PACKAGE_PIN AF19 IOSTANDARD LVCMOS18} [get_ports {btnY[3]}]
set_property -dict {PACKAGE_PIN AE18 IOSTANDARD LVCMOS18} [get_ports {btnY[2]}]
set_property -dict {PACKAGE_PIN AF18 IOSTANDARD LVCMOS18} [get_ports {btnY[1]}]
set_property -dict {PACKAGE_PIN AE17 IOSTANDARD LVCMOS18} [get_ports {btnY[0]}]
set_property -dict {PACKAGE_PIN AF17 IOSTANDARD LVCMOS18} [get_ports {btnX[4]}]
set_property -dict {PACKAGE_PIN AC17 IOSTANDARD LVCMOS18} [get_ports {btnX[3]}]
set_property -dict {PACKAGE_PIN AE15 IOSTANDARD LVCMOS18} [get_ports {btnX[2]}]
set_property -dict {PACKAGE_PIN AF15 IOSTANDARD LVCMOS18} [get_ports {btnX[1]}]
set_property -dict {PACKAGE_PIN AF14 IOSTANDARD LVCMOS18} [get_ports {btnX[0]}]

set_property -dict {PACKAGE_PIN G12 IOSTANDARD LVCMOS33} [get_ports btnL]
set_property -dict {PACKAGE_PIN H12 IOSTANDARD LVCMOS33} [get_ports btnR]

set_property -dict {PACKAGE_PIN AD11 IOSTANDARD LVCMOS15} [get_ports {SW[0]}]
set_property -dict {PACKAGE_PIN AE13 IOSTANDARD LVCMOS15} [get_ports {SW[1]}]
set_property -dict {PACKAGE_PIN AF8 IOSTANDARD LVCMOS15} [get_ports {SW[2]}]
set_property -dict {PACKAGE_PIN AE8 IOSTANDARD LVCMOS15} [get_ports {SW[3]}]
set_property -dict {PACKAGE_PIN AA13 IOSTANDARD LVCMOS15} [get_ports {SW[4]}]
set_property -dict {PACKAGE_PIN AA12 IOSTANDARD LVCMOS15} [get_ports {SW[5]}]
set_property -dict {PACKAGE_PIN Y13 IOSTANDARD LVCMOS15} [get_ports {SW[6]}]
set_property -dict {PACKAGE_PIN Y12 IOSTANDARD LVCMOS15} [get_ports {SW[7]}]
set_property -dict {PACKAGE_PIN AD10 IOSTANDARD LVCMOS15} [get_ports {SW[8]}]
set_property -dict {PACKAGE_PIN AE10 IOSTANDARD LVCMOS15} [get_ports {SW[9]}]
set_property -dict {PACKAGE_PIN AE12 IOSTANDARD LVCMOS15} [get_ports {SW[10]}]
set_property -dict {PACKAGE_PIN AF12 IOSTANDARD LVCMOS15} [get_ports {SW[11]}]
set_property -dict {PACKAGE_PIN AB10 IOSTANDARD LVCMOS15} [get_ports {SW[12]}]
set_property -dict {PACKAGE_PIN AA10 IOSTANDARD LVCMOS15} [get_ports {SW[13]}]
set_property -dict {PACKAGE_PIN AC11 IOSTANDARD LVCMOS15} [get_ports {SW[14]}]
set_property -dict {PACKAGE_PIN AB11 IOSTANDARD LVCMOS15} [get_ports {SW[15]}]

set_property -dict {PACKAGE_PIN C14 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports sdClk]
set_property -dict {PACKAGE_PIN E15 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports sdCmd]
set_property -dict {PACKAGE_PIN D14 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {sdDat[0]}]
set_property -dict {PACKAGE_PIN F13 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {sdDat[1]}]
set_property -dict {PACKAGE_PIN D16 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {sdDat[2]}]
set_property -dict {PACKAGE_PIN E16 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {sdDat[3]}]
set_property -dict {PACKAGE_PIN D15 IOSTANDARD LVCMOS33} [get_ports sdCd]

set_property -dict {PACKAGE_PIN C17 IOSTANDARD LVCMOS33 PULLUP true} [get_ports uartRx]
set_property -dict {PACKAGE_PIN E17 IOSTANDARD LVCMOS33 DRIVE 16 SLEW FAST PULLUP true} [get_ports uartTx]

set_property -dict {PACKAGE_PIN AE22 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports usbADp]
set_property -dict {PACKAGE_PIN AF23 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports usbADn]
set_property -dict {PACKAGE_PIN AF24 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports usbADpEn]
set_property -dict {PACKAGE_PIN AE25 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports usbADnEn]
set_property -dict {PACKAGE_PIN AE23 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports usbBDp]
set_property -dict {PACKAGE_PIN AF25 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports usbBDn]
set_property -dict {PACKAGE_PIN AD25 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports usbBDpEn]
set_property -dict {PACKAGE_PIN AD26 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports usbBDnEn]

set_property -dict {PACKAGE_PIN AE26 IOSTANDARD LVCMOS33} [get_ports rst50an]

set_property -dict {PACKAGE_PIN R17 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {VGAColor[8]}]
set_property -dict {PACKAGE_PIN N18 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {VGAColor[9]}]
set_property -dict {PACKAGE_PIN N19 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {VGAColor[10]}]
set_property -dict {PACKAGE_PIN M19 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {VGAColor[11]}]
set_property -dict {PACKAGE_PIN M20 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {VGAColor[4]}]
set_property -dict {PACKAGE_PIN M21 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {VGAColor[5]}]
set_property -dict {PACKAGE_PIN M17 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {VGAColor[6]}]
set_property -dict {PACKAGE_PIN L19 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {VGAColor[7]}]
set_property -dict {PACKAGE_PIN P18 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports HSync]
set_property -dict {PACKAGE_PIN L18 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {VGAColor[0]}]
set_property -dict {PACKAGE_PIN K21 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {VGAColor[1]}]
set_property -dict {PACKAGE_PIN K20 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {VGAColor[2]}]
set_property -dict {PACKAGE_PIN J19 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {VGAColor[3]}]
set_property -dict {PACKAGE_PIN R18 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports VSync]

